title = "Extended Gitleaks Configuration"

[extend]
# useDefault will extend the default gitleaks config built in to the binary
# the latest version is located at:
# https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml
useDefault = true

[[rules]]
id = "hardcoded-password"
description = "Detect hardcoded passwords"
regex = '''(?i)(password\s*=\s*['"][^'"]+['"])'''
tags = ["key", "password"]

[[rules]]
id = "hardcoded-secret"
description = "Detect hardcoded secrets"
regex = '''(?i)(secret\s*=\s*['"][^'"]+['"])'''
tags = ["key", "secret"]

