repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.17.0
    hooks:
      - id: gitleaks
        args:
          - detect
          - --source=.
          - --config=.gitleaks.toml
          - --no-fail  # Run in informational mode
      