name: Semgrep CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Semgrep
      - name: Install Semgrep
        run: |
          pip install semgrep

      # Step 3: Run Semgrep
      - name: Run Semgrep
        run: |
          semgrep --config p/ci --error