name: Semgrep CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Semgrep
      - name: Install Semgrep
        run: |
          pip install semgrep

      # Step 3: Run Semgrep
      - name: Run Semgrep
        run: |
          semgrep --config p/ci 
      
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t secure-container-app .

      # Step 4: Install Syft
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      # Step 5: Generate SBOM
      - name: Generate SBOM
        run: |
          syft secure-container-app:latest -o json > sbom.json

      # Step 6: Upload SBOM as an Artifact
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json